// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reactivities.Persistence;

#nullable disable

namespace Reactivities.Persistence.Migrations
{
    [DbContext(typeof(ReactivitiesContext))]
    [Migration("20240218145316_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reactivities.Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e852b44-b830-4caa-8299-b2cd840e4f04"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 12, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7342),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("af5dc27e-c894-4934-bb87-d21cfe820e78"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2024, 1, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7358),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("ddb0c2f0-4111-4be5-b576-9f02394c483d"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 3, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7362),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("0a28ca9c-807b-4fe0-b4c2-f6d4060e7b4c"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 4, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7375),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("feecb4cb-4ca2-406d-a7a3-bda5f255d9ed"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 5, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7378),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("5908d63c-088b-4c5d-b1e6-dd70136dfdd9"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 6, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7380),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("d67035d8-781a-4e5b-a1ee-b99a9ff14210"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 7, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7403),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("5d58e449-7e22-4fc9-94e8-db401d99f207"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 8, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7406),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("51dec12e-ecef-4b6d-b70c-8c7997eedf4d"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2024, 9, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7408),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("de5a0bdf-31f7-4d4a-9d34-782df0f9c4ec"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 10, 18, 14, 53, 16, 307, DateTimeKind.Utc).AddTicks(7410),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
